name: sofia
services:
 
  # Sofia Api Gateway 
  sofia-api-gateway:
    build:
      context: sofia-api-gateway
      args:
        DB_IP: sofiadb
        DB_PORT: 3306
        DB_NAME: ${MYSQL_AUTHOR_DB_NAME}
        DB_USERNAME: root
        DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      dockerfile: Dockerfile
    image: sofia-api-gateway
    container_name: sofia-api-gateway
    ports:
      - "15502:15502"
    restart: unless-stopped
    networks:
      - sofia_network

  # Sofia Backend application 
  sofia-backend:
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    build:
      context: backend-container
      args:
        DB_IP: sofiadb
        DB_PORT: 3306
        DB_NAME: ${MYSQL_AUTHOR_DB_NAME}
        DB_APP_NAME: ${MYSQL_APP_DB_NAME}
        DB_USERNAME: root
        DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        REDIS_HOST: sofiaredis
        REDIS_PORT: 6379
        REDIS_PASSWORD: ${REDIS_PASSWORD}
      dockerfile: Dockerfile
    image: sofia-backend
    container_name: sofia-backend
    ports:
      - "15504:15502"
    restart: unless-stopped
    depends_on:
      - sofiadb
      - sofiaredis
    networks:
      - sofia_network 

  # Sofia Frontend application 
  sofia-frontend:
    build:
      context: frontend-container
      dockerfile: Dockerfile
      args:
        BACKEND_URL: ${BACKEND_URL}
    image: sofia-frontend
    container_name: sofia-frontend
    ports:
      - "5000:80"
    restart: unless-stopped
    networks:
      - sofia_network
    volumes:
      - ./frontend-container/test_plugin:/usr/share/nginx/html/assets/ui-plugins/test_plugin:cached
      
  # Sofia Backend Author application
  sofia-backend-author:
    mem_limit: 1024m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx1024m
    build:
      context: backend-author-container
      args:
        DB_IP: sofiadb
        DB_PORT: 3306
        DB_NAME: ${MYSQL_AUTHOR_DB_NAME}
        DB_APP_NAME: ${MYSQL_APP_DB_NAME}
        DB_USERNAME: root
        DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        REDIS_HOST: sofiaredis
        REDIS_PORT: 6379
        REDIS_PASSWORD: ${REDIS_PASSWORD}
      dockerfile: Dockerfile
    image: sofia-backend-author
    container_name: sofia-backend-author
    ports:
      - "15503:15502"
    restart: unless-stopped
    depends_on:
      - sofiadb
      - sofiaredis
    networks:
      - sofia_network

  # Sofia Frontend Author application    
  sofia-frontend-author:
    build:
      context: frontend-author-container
      dockerfile: Dockerfile
      args:
        BACKEND_URL: ${BACKEND_AUTHOR_URL}
    image: sofia-frontend-author
    container_name: sofia-frontend-author
    ports:
      - "5001:80"
    restart: unless-stopped
    networks:
      - sofia_network

  # MariaDb Database of Sofia application 
  sofiadb:
    image: mariadb:10.5
    command: --default-authentication-plugin=mysql_native_password
    container_name: sofiadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_AUTHOR_DB_NAME}
    volumes:
      - sofia-database:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - sofia_network

  # Phpmyadmin web-based application that provides a graphical user interface (GUI) for managing and administering MariaDb Database of Sofia application
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: sofia-db-admin
    restart: unless-stopped
    environment:
      PMA_HOST: sofiadb
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    ports:
      - "4801:80"
    networks:
      - sofia_network

  # Redis is an In-memory data storage application used as a Cache for Sofia Application
  sofiaredis:
    image: "redis:alpine"
    hostname: redis
    container_name: sofiaredis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - sofia_network
    restart: unless-stopped

  # Redis Commander is a web-based graphical user interface (GUI) tool for managing and interacting with Redis server    
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:sofiaredis:6379:1:${REDIS_PASSWORD}
    ports:
      - "8082:8081"
    networks:
      - sofia_network
      
  # Dozzle web-based log viewer that monitors logs generated by Docker containers in real-time
  # Access it on your browser on port 8081   
  dozzle:
    image: amir20/dozzle
    container_name: sofia-logs
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"
    networks:
      - sofia_network  
      
networks:
  sofia_network:
    name: sofia_network
    driver: bridge

volumes:
  sofia-database: ~
